#!/usr/bin/env python3
"""Generate ElevenLabs v4 VO files for SandSync Demo V4."""
import os
import requests
import json

API_KEY = "sk_d796b96b17fcd66c0a89c87dd0e535c1c1194ddb1d21e94e"
VOICE_ID = "EXAVITQu4vr4xnSDxMaL"  # Sarah
MODEL_ID = "eleven_turbo_v2_5"
OUT_DIR = "/Users/loki/projects/sandsync/demo-video/auto/vo"

VO_LINES = [
    ("v4_scene_a_vo", "SandSync is an offline-first AI storytelling platform for Caribbean folklore. Built on PowerSync and Mastra, backed by Supabase, routed by TanStack Router."),
    ("v4_scene_b_vo", "These stories already live here. Generated by our agents, written in Caribbean dialect, illustrated by fal.ai, narrated in Jamaican English by ElevenLabs. Every one stored in local SQLite — not the cloud."),
    ("v4_scene_d_vo", "Five agents. One living story. Papa Bois writes the creative brief. Anansi weaves the chapter in Caribbean dialect. Ogma — the language guardian — judges every word. Only a score of seven-point-five or higher passes. Then Devi narrates, and Imagen paints — running in parallel. Orchestrated entirely by Mastra."),
    ("v4_scene_f_vo", "Complete story — written, judged, narrated, illustrated. The audio lives in Supabase Storage. The text and metadata synced through PowerSync to every device."),
    ("v4_scene_h_vo", "Imagine a parent who generated this story before the family road trip. Now they're in the dead zone. No signal. Kids want their story. Local SQLite has it all. PowerSync already synced it. The network can stay offline."),
]

headers = {
    "xi-api-key": API_KEY,
    "Content-Type": "application/json",
    "Accept": "audio/mpeg",
}

results = []
for name, text in VO_LINES:
    out_path = os.path.join(OUT_DIR, f"{name}.mp3")
    if os.path.exists(out_path):
        size = os.path.getsize(out_path)
        print(f"  ⏭  {name}.mp3 already exists ({size} bytes)")
        results.append((name, out_path, True))
        continue

    print(f"  🎙  Generating: {name}...")
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
    payload = {
        "text": text,
        "model_id": MODEL_ID,
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.8,
            "style": 0.2,
            "use_speaker_boost": True
        }
    }
    resp = requests.post(url, headers=headers, json=payload)
    if resp.status_code == 200:
        with open(out_path, "wb") as f:
            f.write(resp.content)
        size = os.path.getsize(out_path)
        print(f"  ✅  {name}.mp3 saved ({size} bytes)")
        results.append((name, out_path, True))
    else:
        print(f"  ❌  {name} FAILED: {resp.status_code} {resp.text[:200]}")
        results.append((name, None, False))

print("\n--- SUMMARY ---")
for name, path, ok in results:
    status = "✅" if ok else "❌"
    print(f"  {status} {name}")
