#!/usr/bin/env python3
"""
generate_vo_v2.py — Generate ElevenLabs voiceover audio for SandSync demo v3.
New structure: INTRO, A, B, C, D, E (5 timed segs), F, OUTRO
"""

import os
import sys
import json
import subprocess
import requests
import time

VOICE_ID = "dhwafD61uVd8h85wAZSE"  # Denzel — Jamaican
MODEL_ID = "eleven_turbo_v2_5"
VOICE_SETTINGS = {
    "stability": 0.55,
    "similarity_boost": 0.85,
    "style": 0.3,
    "use_speaker_boost": True
}

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
VO_DIR = os.path.join(BASE_DIR, "vo")
os.makedirs(VO_DIR, exist_ok=True)

# VO scripts keyed by filename (without .mp3)
SCENES = {
    # INTRO (0:00–0:15) slides 1+2
    "v3_intro_vo": (
        "Caribbean folklore lives in community — not in the cloud. "
        "And it definitely shouldn't need the cloud to survive."
    ),
    # SCENE A (0:15–0:35) slides 3+5
    "v3_scene_a_vo": (
        "SandSync is an offline-first AI storytelling platform. "
        "PowerSync syncs Supabase to local SQLite in the browser. "
        "Stories live on your device, not just in the cloud."
    ),
    # SCENE B (0:35–0:55) live showcase
    "v3_scene_b_vo": (
        "These are stories already generated by our agents — "
        "illustrated, narrated in Jamaican English, and available offline."
    ),
    # SCENE C part 1 (0:55–1:15) story reader
    "v3_scene_c1_vo": (
        "Narrated by Denzel — a Jamaican ElevenLabs voice. "
        "This story is in your browser's local SQLite right now. "
        "Watch what happens when I cut the network."
    ),
    # SCENE C part 2 (1:15–1:30) offline moment
    "v3_scene_c2_vo": (
        "Still here. That's PowerSync."
    ),
    # SCENE D (1:30–1:40) slides 4+7
    "v3_scene_d_vo": (
        "Five agents. One living story. "
        "Mastra orchestrates the whole thing — with a real LLM-as-judge revision loop."
    ),
    # SCENE E timed segments (1:40–2:20) pipeline
    "v3_scene_e_vo_0s": "I'll type a prompt and let the agents go.",
    "v3_scene_e_vo_8s": "Anansi is writing — Claude Sonnet in authentic Caribbean dialect.",
    "v3_scene_e_vo_16s": "Ogma is judging — seven point five out of ten to pass.",
    "v3_scene_e_vo_24s": "ElevenLabs narrating. fal.ai painting the illustration.",
    "v3_scene_e_vo_35s": "Done. PowerSync broadcasting to every connected device.",
    # SCENE F (2:20–2:40) result
    "v3_scene_f_vo": (
        "Complete story — written, judged, narrated, illustrated, synced. "
        "In about ninety seconds."
    ),
    # OUTRO (2:40–3:00) slides 11+12
    "v3_outro_vo": (
        "Built with PowerSync at the core. "
        "Mastra, Supabase, TanStack, ElevenLabs, fal.ai. "
        "SandSync — where Caribbean folklore lives offline."
    ),
}


def get_api_key():
    result = subprocess.run(
        ["op", "read", "op://OpenClaw/ElevenLabs Secondary API Credentials/credential"],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def generate_audio(api_key: str, text: str, out_path: str, retries: int = 3):
    url = f"https://api.elevenlabs.io/v1/text-to-speech/{VOICE_ID}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json",
    }
    payload = {
        "text": text,
        "model_id": MODEL_ID,
        "voice_settings": VOICE_SETTINGS,
    }
    for attempt in range(retries):
        resp = requests.post(url, headers=headers, json=payload, timeout=60)
        if resp.status_code == 200:
            with open(out_path, "wb") as f:
                f.write(resp.content)
            return True
        elif resp.status_code == 429:
            wait = 10 * (attempt + 1)
            print(f"  Rate limited — waiting {wait}s...")
            time.sleep(wait)
        else:
            print(f"  ERROR {resp.status_code}: {resp.text}")
            if attempt < retries - 1:
                time.sleep(5)
    return False


def get_duration(path: str) -> float:
    result = subprocess.run(
        ["/opt/homebrew/bin/ffprobe", "-v", "quiet",
         "-show_entries", "format=duration",
         "-of", "csv=p=0", path],
        capture_output=True, text=True
    )
    try:
        return float(result.stdout.strip())
    except ValueError:
        return 0.0


def main():
    print("🎙  SandSync VO Generator v2 (v3 video)")
    print("=" * 50)

    api_key = get_api_key()
    print(f"✅ ElevenLabs API key loaded")

    meta = {}

    for name, text in SCENES.items():
        out_path = os.path.join(VO_DIR, f"{name}.mp3")

        if os.path.exists(out_path):
            dur = get_duration(out_path)
            print(f"⏭  {name}.mp3 already exists ({dur:.1f}s) — skipping")
            meta[name] = {"path": out_path, "duration": dur}
            continue

        print(f"🎤 Generating {name}...")
        ok = generate_audio(api_key, text, out_path)
        if ok:
            dur = get_duration(out_path)
            meta[name] = {"path": out_path, "duration": dur}
            print(f"   ✅ {out_path} ({dur:.1f}s)")
            time.sleep(1)  # gentle rate limiting
        else:
            print(f"   ❌ Failed to generate {name}")
            meta[name] = {"path": out_path, "duration": 0.0, "error": True}

    # Save/merge meta
    meta_path = os.path.join(BASE_DIR, "scenes_meta_v2.json")
    existing = {}
    if os.path.exists(meta_path):
        with open(meta_path) as f:
            existing = json.load(f)
    existing["vo"] = meta
    with open(meta_path, "w") as f:
        json.dump(existing, f, indent=2)

    print(f"\n✅ scenes_meta_v2.json written")
    print("\n📊 Summary:")
    for name, m in meta.items():
        dur = m.get("duration", 0)
        print(f"   {name}: {dur:.1f}s")
    total = sum(m.get("duration", 0) for m in meta.values())
    print(f"\n   Total VO: {total:.1f}s")


if __name__ == "__main__":
    main()
