-- Migration 006: fill schema gaps — add missing columns that pipeline generates but never persisted
-- stories: theme, updated_at
-- story_chapters: title

ALTER TABLE stories ADD COLUMN IF NOT EXISTS theme TEXT, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Backfill updated_at for existing rows
UPDATE stories SET updated_at = created_at WHERE updated_at IS NULL;

-- Add trigger to auto-update updated_at on stories
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_stories_updated_at ON stories;
CREATE TRIGGER update_stories_updated_at BEFORE UPDATE ON stories FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE story_chapters ADD COLUMN IF NOT EXISTS title TEXT;

-- PowerSync: existing sync rules will pick up new columns automatically on next sync
COMMENT ON COLUMN stories.theme IS 'Original user story prompt/request';
COMMENT ON COLUMN stories.updated_at IS 'Last updated timestamp, auto-managed by trigger';
COMMENT ON COLUMN story_chapters.title IS 'Chapter title generated by Anansi agent';
